# Generated by Django 5.0.7 on 2024-07-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="top_agent",
            field=models.BooleanField(default=False, verbose_name="Top Agent"),
        ),
    ]
