# Generated by Django 5.0.7 on 2024-07-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_top_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="profile_default.jpg",
                upload_to="",
                verbose_name="Profile Photo",
            ),
        ),
    ]
