# Generated by Django 5.0.7 on 2024-07-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_profile_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="rating",
            new_name="ratings",
        ),
    ]
