# Generated by Django 5.0.7 on 2024-07-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="rating",
        ),
    ]
